src/Entity/Booking.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\PreUpdate;
use Doctrine\ORM\Mapping\PrePersist;
use App\Repository\BookingRepository;
use DateTime;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Constraints\GreaterThan;

/**
 * @ORM\Entity(repositoryClass=BookingRepository::class)
 * @ORM\HasLifecycleCallbacks()
 */
class Booking
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $booker;

    /**
     * @ORM\ManyToOne(targetEntity=Ad::class, inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $ad;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\GreaterThanOrEqual("today", message="La date d'arrivée doit forcemment être superieure à la date actuelle")
     * @Assert\GreaterThan("today",message="Vous ne pouvez reserver qu'a partir de la date de demain")
     */
    private $startDate;

    /**
     * @ORM\Column(type="datetime")
     *
     * @Assert\GreaterThan(
     *  propertyPath="startDate",
     *  message="La date de départ doit être supérieur à la date d'arrivée"
     * )
     */
    private $endDate;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createAt;

    /**
     * @ORM\Column(type="float")
     */
    private $amount;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment;
    
    /**
     * Check that createdAt is always filled and calculate amount
     *
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function createdAt()
    {
        if (empty($this->getCreateAt)) {
            $this->setCreateAt(new \DateTime('now'));
        }
        if (empty($this->amount)) {
            $this->setAmount($this->getDuration() * $this->ad->getPrice());
        }
    }

    /**
     * Return nb of location days
     *
     */
    public function getDuration()
    {
        return $this->getEndDate()->diff($this->getStartDate())->days;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBooker(): ?User
    {
        return $this->booker;
    }

    public function setBooker(?User $booker): self
    {
        $this->booker = $booker;

        return $this;
    }

    public function getAd(): ?Ad
    {
        return $this->ad;
    }

    /**
     * Verify if the date passed is avilable or not
     * 
     * @return null|[]
     */
    public function unvalidateDays()
    {
        $days = $this->ad->getUnbookingDays();
        $myDays = range($this->getStartDate()->getTimestamp(), $this->getEndDate()->getTimestamp(), (24*60*60));
            $mydays = array_map(function ($item) {
                return date("Y-m-d", $item);
            }, $myDays);
        foreach ($days as $daystab) {
            if (count($daystab)>0) {
                if ($sameDate = array_intersect($daystab, $mydays)) {
                    return $sameDate;
                }
                continue;
            }
        }
        return false;
    }


    public function setAd(?Ad $ad): self
    {
        $this->ad = $ad;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getCreateAt(): ?\DateTimeInterface
    {
        return $this->createAt;
    }

    public function setCreateAt(\DateTimeInterface $createAt): self
    {
        $this->createAt = $createAt;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount = $this->getDuration() * $this->ad->getPrice();
    }

    public function setAmount(float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }
}

src/Form/BookingType.php
<?php

namespace App\Form;

use App\Entity\Booking;
use App\Form\ConfigurationType;
use Symfony\Component\Form\AbstractType;
use App\Form\DataTransformer\DateTimeFrenchTransform;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class BookingType extends ConfigurationType
{

    private $transform;
    
    public function __construct(DateTimeFrenchTransform $transform)
    {
        $this->transform = $transform;
    }
    
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add(
                'startDate',
                TextType::class,
                array_merge(
                    $this->getConfiguration(
                        \utf8_decode("Date d'arrivée souhaitée"),
                        "jj/mm/aaaa",
                        true,
                        null,
                    )
                )
            )
            ->add(
                'endDate',
                TextType::class,
                array_merge(
                    $this->getConfiguration(
                        \utf8_decode("Date de départ estimée"),
                        "jj/mm/aaaa",
                        true,
                        null
                    )
                )
            )
            ->add(
                "comment",
                TextareaType::class,
                $this->getConfiguration(
                    "Un commentaire ?",
                    \utf8_decode("Merci de déposer ici votre commentaire...Si vous le désirez"),
                    false
                )
            )
        ;
        $builder-> get('startDate')->addModelTransformer($this->transform);
        $builder-> get('endDate')->addModelTransformer($this->transform);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Booking::class,
        ]);
    }
}

src/Controller/BookingController.php
<?php

namespace App\Controller;

use DateTimeZone;
use App\Entity\Ad;
use App\Entity\Booking;
use App\Entity\Comment;
use App\Form\BookingType;
use App\Form\CommentType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Constraints\Date;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class BookingController extends AbstractController
{

    /**
     * This method allow to add a reservation
     *
     * @param Ad $ad
     * @param Request $request
     * @param EntityManagerInterface $manager
     *
     * @Route("/booking/ad/{slug}", name="ads_add_booking")
     *
     * @IsGranted("ROLE_USER")
     */
    public function addAction(Ad $ad, Request $request, EntityManagerInterface $manager)
    {
        $booking = new Booking();
        $form = $this->createForm(BookingType::class, $booking);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $dateStart = $booking->getStartDate()->getTimestamp();
            $dateEnd = $booking->getEndDate()->getTimestamp();
            $booking->setAd($ad)
                    ->setBooker($this->getUser());
            if ($booking->unvalidateDays()) {
                $unvalidateDays = $booking->unvalidateDays();
                $this->addFlash(
                    'warning',
                    "<h5><strong>Attention !!!</strong></h5>
                    <p>Desolé... ce bien est déjà retenu pour la période du
                    <b>{$this->formatDate($unvalidateDays[0])} au
                    {$this->formatDate($unvalidateDays[count($unvalidateDays)-1])} inclus.</b></p>
                    <p>Veuillez décaler votre réservation si vous le pouvez... Merci!</p>"
                );
                return $this->redirectToRoute("ads_add_booking", ["slug"=>$ad->getSlug()]);
            }
            $manager->persist($booking);
            $manager->flush();
            setlocale(LC_TIME, 'fr_FR.UTF8', 'fr.UTF8', 'fr_FR.UTF-8', 'fr.UTF-8');
            $startDate = strftime('%A %e %B %Y', $dateStart);
            $endDate = strftime('%A %e %B %Y', $dateEnd);

                return $this->redirectToRoute("ad_get_booking", ['id'=>$booking->getId(),'withAlert'=>true]);
        }
        return $this->render(
            'booking/form_booking.html.twig',
            [
                'titre' => "Reservation du bien nommé: &nbsp; <i>".$ad->getTitle()."</i>",
                'ad'=>$ad,
                'booking'=>$booking,
                'form'=> $form->createView()
            ]
        );
    }

    /**
     * This method show details of booking passed
     *
     * @param Booking $booking
     * @param Request $request
     * @param EntityManagerInterface $manager
     *
     * @return Response
     *
     * @Route("/booking/get/{id}", name="ad_get_booking")
     */
    public function getAction(Booking $booking, Request $request, EntityManagerInterface $manager)
    {
        $comment = new Comment();
        $commentForm = $this->createForm(CommentType::class, $comment);
        $commentForm->handleRequest($request);
        if ($commentForm->isSubmitted() && $commentForm->isValid()) {
            $comment->setAd($booking->getAd());
            $comment->setAuthor($this->getUser());
            $manager->persist($comment);
            $manager->flush();
            $this->addFlash(
                'success',
                "<h5>Merci !... Votre avis a bien été pris en compte</h5>"
            );
        }

        return $this->render(
            "/booking/resume_booking.html.twig",
            [
                'booking'=>$booking,
                'comment_form'=> $commentForm->createView()
            ]
        );
    }

    /**
     * This method is used to Format the given date
     *
     * @param [type] $myDate
     *
     * @return void
     */
    private function formatDate($myDate)
    {
        $date = new \DateTime($myDate);
        $date = $date->getTimestamp();
        setlocale(LC_TIME, 'fr_FR.UTF8', 'fr.UTF8', 'fr_FR.UTF-8', 'fr.UTF-8');
        $date = strftime('%A %e %B %Y', $date);
        return $date;
    }
}

templates/booking/resume_booking.html.twig
{% extends "base.html.twig" %}
{% block title %}/ Résumé de location {% endblock %}
{% block body %}
{# Ici commence Alert qui resume les dates de reservations #}
{% if app.request.query.get('withAlert') %}
    <div class="alert alert-success p-4 rounded border border-light">
        <h5><b>Bravo !!!</b></h5>
        <p class='h5'>Votre réservation a bien été effectuée pour
            <b>{{ booking.getDuration() }} nuits</b>&nbsp; à
            <b>{{ booking.ad.getPrice() }} &euro; / nuits</b>&nbsp;soit
            <b>{{ booking.getAmount() }} &euro;</b>
            pour la période du <b>{{ booking.startDate | format_datetime('full', 'none', locale='fr')}} au {{ booking.endDate | format_datetime('full', 'none', locale='fr')}}</b> .
            <a 
            class='btn btn-info p-2 mx-3' 
            href="{{ path('get_ad',{'slug':booking.ad.slug}) }}"
            role='button'>
                Détails de l'offre
            </a>
        </p>
    </div>
{% endif %}
{# Ici commence le titre de la reservation #}
{% set author = booking.ad.author %}
<h1 class="text-center mb-5 pb-5 border-bottom border-grey mx-auto"> Résumé de la location <b><i>{{ booking.getAd().getTitle() }}</i></b></h1>
{# Ici commence le détail de l'hôte #}
<div class="row mx-auto col-12 col-sm-12 col-lg-8 d-flex justify-content-center align-items-baseline">
    <div class="col-sm-12 col-12 col-md-5 col-lg-5 d-flex justify-content-center">
        <dl class="my-1 mt-3 mx-auto col-8 col-md-12 bg bg-light rounded">
            <dt class="my-1 mt-3 mx-auto h3 alert-heading">Votre hôte</dt>
            <dd class="ml-3">
                <a href="{{ path('account_profil', {'slug':author.slug}) }}" 
                    class="text-decoration-none d-flex d-inline align-items-center">
                    <img src="{{ author.picture }}" 
                    alt="image de {{ author.fullname() }}" 
                    class="rounded-circle img-thumbnail thumbail mr-3 mr-md-0 mr-lg-0">
                    <div class="row d-flex align-items-center">
                        <div class="col-12 col-md-12 col-lg-12 d-flex d-wrap justify-content-center mx-auto">{{ author.fullname() }}</div>
                        <div 
                            class="badge badge-primary col-10 col-md-5 col-lg-7 d-flex d-wrap justify-content-center mx-auto p-2">
                            {{ author.ads|length }}
                                {% if author.ads|length>1 %} Annonces  
                                {% else %} Annonce
                                {% endif %}
                        </div>
                    </div>
                </a>
                    <div class="d-flex d-wrap col-12 text-muted">{{ author.introduction }}</div>
            </dd>
            <dt class="my-1 mt-3 mx-auto">Titre de l'annonce choisie</dt>
            <dd class="ml-3">
            {{ booking.ad.title }}
            </dd>
            <img src="{{ booking.ad.coverImage }}" alt="image de {{booking.ad.title}}" class="img-fluid rounded border border-dark mt-3">
            <p class="mt-2 text-muted">{{ booking.ad.introduction }}</p>
                <div>
                    <a href="{{ path('get_ad',{'slug':booking.ad.slug}) }}" class="badge badge-success p-2">En savoir plus</a>
                </div>
            <dt class="my-1 mt-3 mx-auto">Numéro de réservation</dt>
            <dd class="ml-3">{{ booking.Id }}</dd>
            <dt class="my-1 mt-3 mx-auto">Prise de réservation le :</dt>
            <dd class="ml-3">{{ booking.getCreateAt() | format_datetime('full', 'none', locale='fr') }}</dd>
        </dl>
    </div>
    {# Ici commence le détail des dates #}
    <div class="col-sm-12 col-12 col-md-5 col-lg-6 d-flex justify-content-center flex-wrap">
        <dl class="my-1 mt-3 mx-auto col-9 bg bg-light rounded">
            <dt class="my-1 mt-3 mx-auto h3 alert-heading">Vos dates</dt>
            <dt class="my-1 mt-3 mx-auto">Date de réservation</dt>
            <dd class="ml-3">
                Du 
                {{ booking.startDate() | format_datetime('full', 'none', locale='fr') }}
                au
                {{ booking.endDate() | format_datetime('full', 'none', locale='fr') }}
            </dd>
            <dt class="my-1 mt-3 mx-auto">Nombre de nuits ({{booking.ad.price}} &euro;/ nuits )</dt>
            <dd class="ml-3">{{ booking.duration }} nuits</dd>
            <dt class="my-1 mt-3 mx-auto">Montant du séjour</dt>
            <dd class="ml-3">{{ booking.amount() }} &euro;</dd>
            <dt class="my-1 mt-3 mx-auto">Mon commentaire</dt>
            <dd class="ml-3">{{booking.comment | default('Pas de  commentaires') }} </dd>
        </dl>
            <div class="col-9 mt-4 d-flex flex-wrap p-1 border border-grey rounded">
                <h4 class="col-12 mb-3">Votre avis compte !!!</h4>
                <p class="col-12">Confiez-nous votre opinion sur le déroulement de votre séjour.</p>
                <div class="col-12 d-flex justify-content-center">
                {% if date() > date(booking.endDate) %}
                {% set ad = booking.ad %}
                {% if ad.commentFromAuthor(app.user) %} 
                    <div class="col-12 d-flex justify-content-left d-flex flex-wrap">
                        <h5 class="mt-4 mb-3">Commentaire déposé</h5>
                        <blockquote class="col-12"><i> "{{ ad.commentFromAuthor(app.user) }}" </i></blockquote>
                        <div class="col-12 d-flex justify-content-end">
                            <p>Note: {% include "partials/rating_stars.html.twig" with {'rating':ad.ratingFromAuthor(app.user)}%}</p>
                        </div>
                    </div>
                {% else %}
                    {{ form_start(comment_form) }}
                    {{ form_widget(comment_form) }}
                    <div class="d-flex justify-content-center">
                        <button type="submit" class="btn btn-primary">Enregistrer mon commentaire</button> 
                    </div>
                    {{ form_end(comment_form) }}
                {% endif %}
                {% else %}
                <div>
                    <p>Vous ne pourrez déposer de commentaire qu'après votre séjour... Revenez plus tard pour en déposer un</p>
                    <p>Un formulaire apparaîtra ici même afin de vous permettre de noter et commenter votre séjour chez {{booking.ad.author.fullName}}.
                </div>
                {% endif %}
                </div>
            </div>
    </div>
</div>
<div class="endPage"></div>
{% block javascripts %}
    <script src='/public/js/complete_booking.js '></script>
{% endblock %}
{% endblock %}